#################################################################
#  Confluence REST API Documentation
#  https://docs.atlassian.com/ConfluenceServer/rest/7.3.1/#api/
#################################################################
###

# SPACES https://docs.atlassian.com/ConfluenceServer/rest/7.2.0/#api/space-spaces
GET https://confluence.ecmwf.int/rest/api/space?type=global&limit=100&expand=metadata.labels,description.view,description.plain,icon


###

# curl -u admin:admin -X GET "http://localhost:8080/confluence/rest/api/content/12345/property"
GET https://confluence.ecmwf.int/rest/api/content/146654213/property
#Authorization: Basic admin admin

###

# curl --request GET
#  --url 'https://your-domain.atlassian.net/wiki/rest/api/content'
#  --header 'Accept: application/json'
GET https://confluence.ecmwf.int/display/UDOC
Accept: application/json

###

GET https://confluence.ecmwf.int/rest/api/content?spaceKey=UDOC&title=ecCodes+Frequently+Asked+Questions+-+FAQs&expand=space,body.view,version,container
Accept: application/json

###
GET https://confluence.ecmwf.int/rest/api/content/140385202?expand=history,version,metadata.labels,body.view,body.view,body.storage
Accept: application/json

###
GET https://confluence.ecmwf.int/rest/api/content/143036940?expand=body.storage,metadata.labels,space,body.view,version,container
Accept: application/json

###
# Returns information about a space.
GET https://confluence.ecmwf.int/rest/api/space/CKB?expand=description
Accept: application/json

###
# Get all pages in space
GET https://confluence.ecmwf.int/rest/api/space/CKB/content?expand=history&limit=500&start=0
Accept: application/json

###
# Get all pages in space
GET https://confluence.ecmwf.int/rest/api/content?type=page&spaceKey=CKB&start=0&limit=1&expand=history,version,metadata.labels,body.view,body.view,body.storage
Accept: application/json
